// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqF90hybWFAGOSG5f8C8xQIxvs5_06fcY',
    appId: '1:38672009026:web:b414551a92dac74af02adb',
    messagingSenderId: '38672009026',
    projectId: 'qr-barangku-app',
    authDomain: 'qr-barangku-app.firebaseapp.com',
    storageBucket: 'qr-barangku-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxcLUaCcDcwVrYlchn6aiDMpP3t-XVZM',
    appId: '1:38672009026:android:f8025013fea30835f02adb',
    messagingSenderId: '38672009026',
    projectId: 'qr-barangku-app',
    storageBucket: 'qr-barangku-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYGRcAQCAyZoeNg0MxV5_ACL89Y6QWkk',
    appId: '1:38672009026:ios:ac8048ed35ab0887f02adb',
    messagingSenderId: '38672009026',
    projectId: 'qr-barangku-app',
    storageBucket: 'qr-barangku-app.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
